import maze_builder


def encontrar_posicao(labirinto, elemento):
    for r in range(len(labirinto)):
        for c in range(len(labirinto[0])):
            if labirinto[r][c] == elemento:
                return (r, c)
    return None


def resolver_dfs(labirinto, inicio, fim, parede_val=1):
    pilha = [(inicio, [inicio])]
    visitados = {inicio}
    direcoes = [(-1, 0), (1, 0), (0, -1), (0, 1)]

    while pilha:
        (r, c), caminho = pilha.pop()

        if (r, c) == fim:
            return caminho

        for dr, dc in direcoes:
            nr, nc = r + dr, c + dc
            if 0 <= nr < len(labirinto) and 0 <= nc < len(labirinto[0]):
                if labirinto[nr][nc] != parede_val and (nr, nc) not in visitados:
                    visitados.add((nr, nc))
                    pilha.append(((nr, nc), caminho + [(nr, nc)]))

    return None


def desenhar_labirinto_com_caminho(labirinto, caminho, queijo='.', caminho_simbolo='*'):
    grid_visual = [linha.copy() for linha in labirinto]

    for r, c in caminho:
        if grid_visual[r][c] not in (queijo, 'S'):
            grid_visual[r][c] = caminho_simbolo

    return grid_visual


if __name__ == '__main__':
    m, n = 8, 8
    ROOM = 0
    WALL = 'W'
    CHEESE = '*'

    labirinto = maze_builder.generate_maze(m, n, room=ROOM, wall=WALL, cheese=CHEESE)

    inicio = (1, 1)
    fim = encontrar_posicao(labirinto, CHEESE)

    if not fim:
        raise ValueError("O queijo não foi encontrado no labirinto gerado.")

    print("=" * 45)
    print(" LABIRINTO ORIGINAL GENERATED BY MAZE_BUILDER ")
    print("=" * 45)
    maze_builder.print_maze(labirinto)
    print(f"\nInício: {inicio} | Queijo: {fim}\n")

    caminho = resolver_dfs(labirinto, inicio, fim, parede_val=WALL)

    if caminho:
        print("=" * 45)
        print(" LABIRINTO RESOLVIDO (CAMINHO DFS ' * ') ")
        print("=" * 45)
        labirinto_resolvido = desenhar_labirinto_com_caminho(
            labirinto, caminho, queijo=CHEESE, caminho_simbolo='*'
        )
        maze_builder.print_maze(labirinto_resolvido)

        print("\n--- Estatísticas do Trajeto ---")
        print(f"Total de passos: {len(caminho)}")
        print(f"Caminho (coordenadas): {caminho}")
    else:
        print("Nenhum caminho foi encontrado até o queijo.")